#ECG Signal Analyzer settings
#Mon Jun 08 05:37:56 EEST 2026
defaultAnalysisMode=Full signal
defaultWindowSize=5000
showAnnotationsByDefault=true
showGridByDefault=true
showRPeaksByDefault=true
showSuspiciousSegmentsByDefault=true
